'''
The following settings should be defined in your global settings

SHA_PRE and SHA_POST_SECRET have to be set in the ogone admin
Can be any random value. Its just something secret both us and ogone need to know.

Note that the default hash method is set to sha512
Change this in your ogone admin interface

'''

try:
    from django.conf import settings
except ImportError:
    # We do not need Django to used this package
    settings = {}

#These four you probably want to change
PSPID = getattr(settings, 'OGONE_PSPID', None)
SHA_PRE_SECRET = getattr(settings, 'OGONE_SHA_PRE_SECRET', None)
SHA_POST_SECRET = getattr(settings, 'OGONE_SHA_POST_SECRET', None)
CURRENCY = getattr(settings, 'OGONE_CURRENCY', 'EUR')

#only touch these if you know whats happening :P
HASH_METHOD = getattr(settings, 'OGONE_HASH_METHOD', 'sha512')
#for other hashmethods see http://docs.python.org/library/hashlib.html
#ogone default is sha1
PRODUCTION = not getattr(settings, 'DEBUG', True)

# Standard URLs. We might want to override these in the future for some
# reason.
TEST_URL = getattr(settings, "OGONE_TEST_URL",
    "https://secure.ogone.com/ncol/test/orderstandard.asp")
PROD_URL = getattr(settings, "OGONE_PROD_URL",
    "https://secure.ogone.com/ncol/prod/orderstandard.asp")

# DirectLink
USERID = getattr(settings, 'OGONE_USERID', None)
PSWD = getattr(settings, 'OGONE_PSWD', None)

DIRECT_LINK_TEST_URL = getattr(settings, "OGONE_DIRECT_LINK_TEST_URL",
    "https://secure.ogone.com/ncol/test/maintenancedirect.asp")
DIRECT_LINK_PROD_URL = getattr(settings, "OGONE_DIRECT_LINK_PROD_URL",
    "https://secure.ogone.com/ncol/prod/maintenancedirect.asp")

SHA_IN_WHITELIST = getattr(settings, 'OGONE_SHA_IN_WHITELIST', [
    'ACCEPTANCE',
    'ACCEPTURL',
    'ADDMATCH',
    'ADDRMATCH',
    'AIAGIATA',
    'AIAIRNAME',
    'AIAIRTAX',
    'AIBOOKIND*XX*',
    'AICARRIER*XX*',
    'AICHDET',
    'AICLASS*XX*',
    'AICONJTI',
    'AIDEPTCODE',
    'AIDESTCITY*XX*',
    'AIDESTCITYL*XX*',
    'AIEXTRAPASNAME*XX*',
    'AIEYCD',
    'AIFLDATE*XX*',
    'AIFLNUM*XX*',
    'AIGLNUM',
    'AIINVOICE',
    'AIIRST',
    'AIORCITY*XX*',
    'AIORCITYL*XX*',
    'AIPASNAME',
    'AIPROJNUM',
    'AISTOPOV*XX*',
    'AITIDATE',
    'AITINUM',
    'AITINUML*XX*',
    'AITYPCH',
    'AIVATAMNT',
    'AIVATAPPL',
    'ALIAS',
    'ALIASOPERATION',
    'ALIASUSAGE',
    'ALLOWCORRECTION',
    'AMOUNT',
    'AMOUNT*XX*',
    'AMOUNTHTVA',
    'AMOUNTTVA',
    'BACKURL',
    'BATCHID',
    'BGCOLOR',
    'BLVERNUM',
    'BRAND',
    'BRANDVISUAL',
    'BUTTONBGCOLOR',
    'BUTTONTXTCOLOR',
    'CANCELURL',
    'CARDNO',
    'CATALOGURL',
    'CAVV_3D',
    'CAVVALGORITHM_3D',
    'CERTID',
    'CHECK_AAV',
    'CIVILITY',
    'CN',
    'COM',
    'COMPLUS',
    'COSTCENTER',
    'COSTCODE',
    'CREDITCODE',
    'CUID',
    'CURRENCY',
    'CVC',
    'CVCFLAG',
    'DATA',
    'DATATYPE',
    'DATEIN',
    'DATEOUT',
    'DECLINEURL',
    'DEVICE',
    'DISCOUNTRATE',
    'DISPLAYMODE',
    'ECI',
    'ECI_3D',
    'ECOM_BILLTO_POSTAL_CITY',
    'ECOM_BILLTO_POSTAL_COUNTRYCODE',
    'ECOM_BILLTO_POSTAL_NAME_FIRST',
    'ECOM_BILLTO_POSTAL_NAME_LAST',
    'ECOM_BILLTO_POSTAL_POSTALCODE',
    'ECOM_BILLTO_POSTAL_STREET_LINE1',
    'ECOM_BILLTO_POSTAL_STREET_LINE2',
    'ECOM_BILLTO_POSTAL_STREET_NUMBER',
    'ECOM_CONSUMERID',
    'ECOM_CONSUMER_GENDER',
    'ECOM_CONSUMEROGID',
    'ECOM_CONSUMERORDERID',
    'ECOM_CONSUMERUSERALIAS',
    'ECOM_CONSUMERUSERPWD',
    'ECOM_CONSUMERUSERID',
    'ECOM_PAYMENT_CARD_EXPDATE_MONTH',
    'ECOM_PAYMENT_CARD_EXPDATE_YEAR',
    'ECOM_PAYMENT_CARD_NAME',
    'ECOM_PAYMENT_CARD_VERIFICATION',
    'ECOM_SHIPTO_COMPANY',
    'ECOM_SHIPTO_DOB',
    'ECOM_SHIPTO_ONLINE_EMAIL',
    'ECOM_SHIPTO_POSTAL_CITY',
    'ECOM_SHIPTO_POSTAL_COUNTRYCODE',
    'ECOM_SHIPTO_POSTAL_NAME_FIRST',
    'ECOM_SHIPTO_POSTAL_NAME_LAST',
    'ECOM_SHIPTO_POSTAL_NAME_PREFIX',
    'ECOM_SHIPTO_POSTAL_POSTALCODE',
    'ECOM_SHIPTO_POSTAL_STREET_LINE1',
    'ECOM_SHIPTO_POSTAL_STREET_LINE2',
    'ECOM_SHIPTO_POSTAL_STREET_NUMBER',
    'ECOM_SHIPTO_TELECOM_FAX_NUMBER',
    'ECOM_SHIPTO_TELECOM_PHONE_NUMBER',
    'ECOM_SHIPTO_TVA',
    'ED',
    'EMAIL',
    'EXCEPTIONURL',
    'EXCLPMLIST',
    'EXECUTIONDATE*XX*',
    'FACEXCL*XX*',
    'FACTOTAL*XX*',
    'FIRSTCALL',
    'FLAG3D',
    'FONTTYPE',
    'FORCECODE1',
    'FORCECODE2',
    'FORCECODEHASH',
    'FORCEPROCESS',
    'FORCETP',
    'GENERIC_BL',
    'GIROPAY_ACCOUNT_NUMBER',
    'GIROPAY_BLZ',
    'GIROPAY_OWNER_NAME',
    'GLOBORDERID',
    'GUID',
    'HDFONTTYPE',
    'HDTBLBGCOLOR',
    'HDTBLTXTCOLOR',
    'HEIGHTFRAME',
    'HOMEURL',
    'HTTP_ACCEPT',
    'HTTP_USER_AGENT',
    'INCLUDE_BIN',
    'INCLUDE_COUNTRIES',
    'INVDATE',
    'INVDISCOUNT',
    'INVLEVEL',
    'INVORDERID',
    'ISSUERID',
    'IST_MOBILE',
    'ITEM_COUNT',
    'ITEMATTRIBUTES*XX*',
    'ITEMCATEGORY*XX*',
    'ITEMCOMMENTS*XX*',
    'ITEMDESC*XX*',
    'ITEMDISCOUNT*XX*',
    'ITEMID*XX*',
    'ITEMNAME*XX*',
    'ITEMPRICE*XX*',
    'ITEMQUANT*XX*',
    'ITEMQUANTORIG*XX*',
    'ITEMUNITOFMEASURE*XX*',
    'ITEMVAT*XX*',
    'ITEMVATCODE*XX*',
    'ITEMWEIGHT*XX*',
    'LANGUAGE',
    'LEVEL1AUTHCPC',
    'LIDEXCL*XX*',
    'LIMITCLIENTSCRIPTUSAGE',
    'LINE_REF',
    'LINE_REF1',
    'LINE_REF2',
    'LINE_REF3',
    'LINE_REF4',
    'LINE_REF5',
    'LINE_REF6',
    'LIST_BIN',
    'LIST_COUNTRIES',
    'LOGO',
    'MAXITEMQUANT*XX*',
    'MERCHANTID',
    'MODE',
    'MTIME',
    'MVER',
    'NETAMOUNT',
    'OPERATION',
    'ORDERID',
    'ORDERSHIPCOST',
    'ORDERSHIPTAX',
    'ORDERSHIPTAXCODE',
    'ORIG',
    'OR_INVORDERID',
    'OR_ORDERID',
    'OWNERADDRESS',
    'OWNERADDRESS2',
    'OWNERCTY',
    'OWNERTELNO',
    'OWNERTOWN',
    'OWNERZIP',
    'PAIDAMOUNT',
    'PARAMPLUS',
    'PARAMVAR',
    'PAYID',
    'PAYMETHOD',
    'PM',
    'PMLIST',
    'PMLISTPMLISTTYPE',
    'PMLISTTYPE',
    'PMLISTTYPEPMLIST',
    'PMTYPE',
    'POPUP',
    'POST',
    'PSPID',
    'PSWD',
    'REF',
    'REFER',
    'REFID',
    'REFKIND',
    'REF_CUSTOMERID',
    'REF_CUSTOMERREF',
    'REGISTRED',
    'REMOTE_ADDR',
    'REQGENFIELDS',
    'RTIMEOUT',
    'RTIMEOUTREQUESTEDTIMEOUT',
    'SCORINGCLIENT',
    'SETT_BATCH',
    'SID',
    'STATUS_3D',
    'SUBSCRIPTION_ID',
    'SUB_AM',
    'SUB_AMOUNT',
    'SUB_COM',
    'SUB_COMMENT',
    'SUB_CUR',
    'SUB_ENDDATE',
    'SUB_ORDERID',
    'SUB_PERIOD_MOMENT',
    'SUB_PERIOD_MOMENT_M',
    'SUB_PERIOD_MOMENT_WW',
    'SUB_PERIOD_NUMBER',
    'SUB_PERIOD_NUMBER_D',
    'SUB_PERIOD_NUMBER_M',
    'SUB_PERIOD_NUMBER_WW',
    'SUB_PERIOD_UNIT',
    'SUB_STARTDATE',
    'SUB_STATUS',
    'TAAL',
    'TAXINCLUDED*XX*',
    'TBLBGCOLOR',
    'TBLTXTCOLOR',
    'TID',
    'TITLE',
    'TOTALAMOUNT',
    'TP',
    'TRACK2',
    'TXTBADDR2',
    'TXTCOLOR',
    'TXTOKEN',
    'TXTOKENTXTOKENPAYPAL',
    'TYPE_COUNTRY',
    'UCAF_AUTHENTICATION_DATA',
    'UCAF_PAYMENT_CARD_CVC2',
    'UCAF_PAYMENT_CARD_EXPDATE_MONTH',
    'UCAF_PAYMENT_CARD_EXPDATE_YEAR',
    'UCAF_PAYMENT_CARD_NUMBER',
    'USERID',
    'USERTYPE',
    'VERSION',
    'WBTU_MSISDN',
    'WBTU_ORDERID',
    'WEIGHTUNIT',
    'WIN3DS',
    'WITHROOT'
])

SHA_OUT_WHITELIST = getattr(settings, 'OGONE_SHA_OUT_WHITELIST', [
    'AAVADDRESS',
    'AAVCHECK',
    'AAVZIP',
    'ACCEPTANCE',
    'ALIAS',
    'AMOUNT',
    'BIN',
    'BRAND',
    'CARDNO',
    'CCCTY',
    'CN',
    'COMPLUS',
    'CREATION_STATUS',
    'CURRENCY',
    'CVCCHECK',
    'DCC_COMMPERCENTAGE',
    'DCC_CONVAMOUNT',
    'DCC_CONVCCY',
    'DCC_EXCHRATE',
    'DCC_EXCHRATESOURCE',
    'DCC_EXCHRATETS',
    'DCC_INDICATOR',
    'DCC_MARGINPERCENTAGE',
    'DCC_VALIDHOURS',
    'DIGESTCARDNO',
    'ECI',
    'ED',
    'ENCCARDNO',
    'IP',
    'IPCTY',
    'NBREMAILUSAGE',
    'NBRIPUSAGE',
    'NBRIPUSAGE_ALLTX',
    'NBRUSAGE',
    'NCERROR',
    'ORDERID',
    'PAYID',
    'PM',
    'SCO_CATEGORY',
    'SCORING',
    'STATUS',
    'SUBBRAND',
    'SUBSCRIPTION_ID',
    'TRXDATE',
    'VC'
])
